### ISSUE TITLE
returns error if I empty my cart... the free gift requires items to be in your cart

### ISSUE THREAD

**Issue by ed-houston** [ankitpokhrel/WooCommerce-Multiple-Free-Gift#10]
We have a free gift setup in which you only qualify if you have at least 1 item in your cart.  If we add an item to the cart, then select the free gift, then we remove the only item in the cart (so the only item remaining is the free gift), we then get the following error:
Call to undefined method WC_Cart::remove_cart_item() in /home/batteriesinc/public_html/wp-content/plugins/woocommerce-multiple-free-gift/lib/WFG_Frontend.class.php on line 254

**Comment by ankitpokhrel** [comment]
Which version of WooCommerce and WooCommerce Multiple Free Gift are you using?

**Comment by ed-houston** [comment]
woocommerce: 2.2.10

woocommerce multiple free gift: 1.1.0

Ed Houston
1323 May River Rd, Suite 200
Bluffton, South Carolina 29910
Cell: 843.290.4692 <tel:%20843.290.4692>
Email: Ed@GRP46.com <mailto:%20Ed@GRP46.com>
Website: www.GRP46.com <http://www.grp46.com/>
LinkedIn: www.linkedin.com/in/douglasedwardhouston <http://www.linkedin.com/in/douglasedwardhouston>

**Comment by ankitpokhrel** [comment]
Sorry the plugin only works with WooCommerce 2.3+. See [here](https://github.com/ankitpokhrel/WooCommerce-Multiple-Free-Gift#compatiblity).

**Comment by ed-houston** [comment]
Thanks for the quick reply
Ed Houston
1323 May River Rd, Suite 200
Bluffton, South Carolina 29910
Cell: 843.290.4692 <tel:%20843.290.4692>
Email: Ed@GRP46.com <mailto:%20Ed@GRP46.com>
Website: www.GRP46.com <http://www.grp46.com/>
LinkedIn: www.linkedin.com/in/douglasedwardhouston <http://www.linkedin.com/in/douglasedwardhouston>
