### ISSUE TITLE
Uncaught TypeError: n is not a function - ajax-chosen.jquery.min.js:2

### ISSUE THREAD

**Issue by PHGterence** [ankitpokhrel/WooCommerce-Multiple-Free-Gift#11]
Getting this error when searching for a gift on a Woocommerce product page. Going to try look into this but I thought I would mention it

**Comment by ankitpokhrel** [comment]
Which version of WooCommerce and WordPress are you using?

**Comment by PHGterence** [comment]
WordPress 4.0.8
Woocommerce Version 2.2.6

**Comment by ankitpokhrel** [comment]
[The plugin is only supported from WooCommerce ver 2.3+](https://github.com/ankitpokhrel/WooCommerce-Multiple-Free-Gift#compatiblity). Could you please check this in WCv2.3+ and let me know?
