### ISSUE TITLE
The Gift Popup appears in a loop until the user picks "No thanks"

### ISSUE THREAD

**Issue by mariusghitulescu** [ankitpokhrel/WooCommerce-Multiple-Free-Gift#22]
Hey @ankitpokhrel ,

As in these 2 issues ([1](https://wordpress.org/support/topic/keeps-popping-up-with-the-gift-dialog/) and [2](https://wordpress.org/support/topic/not-working-here-too/) ), the plugin shows the popup on the checkout page. 
After you select the Gifts and click "Add Free Gifts", the gifts will be added, the page will reload and the popup will appear again, allowing the user to ultimately select all the possible items as Free Gifts.

The Popup will continue to appear until the user clicks No Thanks.

If it helps, I'm using this with OceanWP.

**Comment by ankitpokhrel** [comment]
Fixed https://github.com/ankitpokhrel/WooCommerce-Multiple-Free-Gift/commit/8c993d8ba2a3fb547c637faaafe3bff311b693db
