### ISSUE TITLE
popup in the checkout  page?

### ISSUE THREAD

**Issue by wireinet** [ankitpokhrel/WooCommerce-Multiple-Free-Gift#26]
Hello! May i see popup overlay window  in the checkout page? In  my  site i have plugin flyout cart with icon with all cart items and only one button - go to checkout page! oops and no bonus!!! 
Only if users go to your cart - it's works well - all works

how i can  change logic  - i want to see popup in  checkout page also

**Comment by ankitpokhrel** [comment]
This feature is available in [premium version](https://ankitpokhrel.com/explore/downloads/woocommerce-multiple-free-gift-plugin-pro/).

**Comment by wireinet** [comment]
Thank  you!
