### ISSUE TITLE
Change the

### ISSUE THREAD

**Issue by jorgept** [ankitpokhrel/WooCommerce-Multiple-Free-Gift#27]
For best accuracy of some themes.
Add option, to display the gift in popup/modal or not... if not, display in a cart/chekout, in a flex-box.
For the customer can add the gift to the cart.
And, in adittion, the possibility to display the gift in the single product page.

Is a excellent improvement.

Thanks in advanced.

**Comment by ankitpokhrel** [comment]
@jorgept Thank you for suggestion. A pull request is always helpful :)
